### ISSUE TITLE
/pb command exception

### ISSUE THREAD

**Issue by 0zelot** [jakeryang/SimplePaintball#1]
> org.bukkit.command.CommandException: Unhandled exception executing command 'pb' in plugin Simple_PaintBall v0.2.3.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-498]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1790) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1598) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-498]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-498]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-498]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.borgdude.paintball.commands.PaintballCommand.onCommand(PaintballCommand.java:33) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-498]
	... 15 more

>

**Comment by jakegut** [comment]
This is a common issue that needs to be fixed, thanks for creating an issue for it. I believe this happens when you use the /pb command on it's own. So just go ahead and use commands and it should behave like expected

**Comment by 0zelot** [comment]
You're right, /pb <subcommand> is working. Thanks for help.

**Comment by jakegut** [comment]
Issue still needs to be resolved to avoid confusion, reopening.

**Comment by jakegut** [comment]
Resolved in commit
