### ISSUE TITLE
Major bug with plugin

### ISSUE THREAD

**Issue by Dgretty** [jakeryang/SimplePaintball#2]
Setup the plugin correctly, and was working fine.
About 12 hours later 2 of my players were stuck in the game, and were receiving the configured reward ammount every second. So they were receiving $2,500 every second for about 20 minutes. I finally noticed it in console, as it was spamming the same error constantly. 

Here is the error, i have included the log, but it is quite large due to the errors.

[latest.log](https://github.com/jakeryang/SimplePaintball/files/3288889/latest.log)

[12:07:27] [Server thread/WARN]: [Simple_PaintBall] Task #1011431 for Simple_PaintBall v0.2.6 generated an exception
java.lang.NullPointerException: null
	at com.borgdude.paintball.objects.Arena.restoreInventory(Arena.java:691) ~[?:?]
	at com.borgdude.paintball.objects.Arena.kickPlayers(Arena.java:632) ~[?:?]
	at com.borgdude.paintball.objects.Arena.stopGame(Arena.java:526) ~[?:?]
	at com.borgdude.paintball.objects.Arena$3.run(Arena.java:308) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.2.jar:git-Paper-82]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1129) ~[patched_1.14.2.jar:git-Paper-82]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-82]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[patched_1.14.2.jar:git-Paper-82]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.14.2.jar:git-Paper-82]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[12:07:27] [Craft Scheduler Thread - 3607/WARN]: [Simple_PaintBall] Plugin Simple_PaintBall v0.2.6 generated an exception while executing task 1029810
java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (-2.9433333333333334)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.14.2.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_14_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:158) ~[patched_1.14.2.jar:git-Paper-82]
	at com.borgdude.paintball.objects.Arena$1.run(Arena.java:96) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-82]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.2.jar:git-Paper-82]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.2.jar:git-Paper-82]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by jakegut** [comment]
Thank you for the detailed issue. I'll be busy the next couple of days, but I'll do my best to fix this as soon as possible.

**Comment by jakegut** [comment]
Just made a release that will stop the infinite loop, but it may cause some players to lose their inventory when they leave the game. If this happens check the console for errors.

https://github.com/jakeryang/SimplePaintball/releases/tag/0.2.6.4-alpha
