### ISSUE TITLE
Error on enable plugin

### ISSUE THREAD

**Issue by jakegut** [jakeryang/SimplePaintball#6]
When enabling the plugin, all of the worlds aren't fully loaded. When getting the signs from the config, it gets the block from the location and the world so the world returns a null value and the plugin crashes.

```
[19:14:30 ERROR]: Error occurred while enabling Simple_PaintBall v0.3.4-alpha.1 (Is it up to date?)
java.lang.NullPointerException: null
        at com.borgdude.paintball.managers.ArenaManager.getArenas(ArenaManager.java:267) ~[?:?]
        at com.borgdude.paintball.managers.ArenaManager.getArenas(ArenaManager.java:288) ~[?:?]
        at com.borgdude.paintball.Main.onEnable(Main.java:81) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-192]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-192]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-192]
        at 
```

**Comment by jakegut** [comment]
This error has not been happening for a while, closing.
