### ISSUE TITLE
Support for Version 1.15.1

### ISSUE THREAD

**Issue by AdrianR25** [jakeryang/SimplePaintball#7]
I'm currently using the plugin with the latest version of Paper MC for Minecraft 1.15.1 and works fine, but it looks like it's unstable, since it removed all the arenas. I don't have any error messages though.

**Comment by jakegut** [comment]
> it looks like it's unstable, since it removed all the arenas

This is a common bug. Which version of Simple Paintball are you using? This bug should've been fixed in the latest update: v0.3.4-alpha.3

**Comment by AdrianR25** [comment]
I'm using the latest version (v0.3.4-alpha-3). Now I have an error message. This appeared at startup:
`[17:20:50 INFO]: Simple Paintball Stats Disabled
[17:20:50 ERROR]: Error occurred while enabling Simple_PaintBall v0.3.4-alpha.3 (Is it up to date?)
java.lang.NullPointerException: null
        at org.bukkit.Location.getBlock(Location.java:133) ~[patched_1.15.1.jar:git-Paper-33]
        at com.borgdude.paintball.objects.Arena.updateSigns(Arena.java:174) ~[?:?]
        at com.borgdude.paintball.managers.ArenaManager.getArenas(ArenaManager.java:251) ~[?:?]
        at com.borgdude.paintball.managers.ArenaManager.getArenas(ArenaManager.java:266) ~[?:?]
        at com.borgdude.paintball.Main.onEnable(Main.java:81) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-33]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-33]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-33]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-33]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[17:20:50 INFO]: [Simple_PaintBall] Disabling Simple_PaintBall v0.3.4-alpha.3
[17:20:50 INFO]: PaintBall Disabled`

The arenas save when created and work perfectly until I restart the server.

**Comment by jakegut** [comment]
This is a work around for the arenas until I release a new update. Use `/pb save` whenever you activate an arena or recreate all of your arenas. This will force-save all activated arenas. Sorry for the inconvenience.

**Comment by AdrianR25** [comment]
Ok, thanks. I'm looking forward to the next update :)

**Comment by jakegut** [comment]
Reopened as 1.15.1 is not supported just yet.

**Comment by jakegut** [comment]
Update dependencies to support 1.15.1. No errors were found but will hold on closing this issue until there are no problems upon release for 1.15.1.

**Comment by AdrianR25** [comment]
It worked perfectly using this command when I created all the arenas.

> This is a work around for the arenas until I release a new update. Use `/pb save` whenever you activate an arena or recreate all of your arenas. This will force-save all activated arenas. Sorry for the inconvenience.
