### ISSUE TITLE
Error on startup v0.3.4-alpha.3

### ISSUE THREAD

**Issue by jakegut** [jakeryang/SimplePaintball#8]
I'm using the latest version (v0.3.4-alpha-3). Now I have an error message. This appeared at startup:
`[17:20:50 INFO]: Simple Paintball Stats Disabled
[17:20:50 ERROR]: Error occurred while enabling Simple_PaintBall v0.3.4-alpha.3 (Is it up to date?)
java.lang.NullPointerException: null
        at org.bukkit.Location.getBlock(Location.java:133) ~[patched_1.15.1.jar:git-Paper-33]
        at com.borgdude.paintball.objects.Arena.updateSigns(Arena.java:174) ~[?:?]
        at com.borgdude.paintball.managers.ArenaManager.getArenas(ArenaManager.java:251) ~[?:?]
        at com.borgdude.paintball.managers.ArenaManager.getArenas(ArenaManager.java:266) ~[?:?]
        at com.borgdude.paintball.Main.onEnable(Main.java:81) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-33]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-33]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-33]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-33]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-33]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[17:20:50 INFO]: [Simple_PaintBall] Disabling Simple_PaintBall v0.3.4-alpha.3
[17:20:50 INFO]: PaintBall Disabled`

The arenas save when created and work perfectly until I restart the server.

_Originally posted by @AdrianR25 in https://github.com/jakeryang/SimplePaintball/issues/7#issuecomment-570798416_

**Comment by jakegut** [comment]
@AdrianR25 This error usually occurs when the location of the world is non-existent. Did you happen to delete a world when there was sign in one of them? I can make a workaround for this but I'm curious if this is the case.

**Comment by AdrianR25** [comment]
I didn't delete any worlds, neither the lobby nor the arenas. I just restarted the server. I remember that there were duplicated locations in the arenas file but there aren't anymore. Maybe it's a saving error? since using the `/pb save` command seems to have fixed it.
